### ISSUE TITLE
Error when using custom streaming service

### ISSUE THREAD

**Issue by nikriek** [rahims/SoCo#44]
I found a good way to stream songs from SoundCloud to my Sonos, but unfortunately it doesn't really work with this (very cool) API. Any idea why this does happen?

```
>>> track = sonos.get_current_track_info()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.macosx-10.9-intel/egg/soco.py", line 680, in get_current_track_info
AttributeError: 'NoneType' object has no attribute 'encode'
```

I'm not a python pro, that's why I can't fix it.

**Comment by nikriek** [comment]
Was a terminal problem…
