### ISSUE TITLE
No route to host

### ISSUE THREAD

**Issue by shining01** [rahims/SoCo#48]
Hello,

i get the following error after this command: python sonoshell.py 192.168.10.27 play. Why?

Traceback (most recent call last):
  File "sonoshell.py", line 34, in <module>
    print sonos.play()
  File "/usr/local/lib/python2.7/dist-packages/soco/core.py", line 439, in play
    ('Speed', 1)
  File "/usr/local/lib/python2.7/dist-packages/soco/services.py", line 158, in _dispatcher
    return self.send_command(action, _args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/soco/services.py", line 330, in send_command
    self.base_url + self.control_url, headers=headers, data=body)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 94, in post
    return request('post', url, data=data, json=json, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 407, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(113, 'No route to host'))

**Comment by KennethNielsen** [comment]
Hallo @shining01 

Development on SoCo has been moved to: https://github.com/SoCo/SoCo. I suggest you check out whether the version there has the same issue, and if that is the case, raise the issue there.

**Comment by KennethNielsen** [comment]
All development of SoCo has moved to https://github.com/SoCo/SoCo. Please re-postyour question there. We also have a google group and an IRC channel which are the preferred media for support.
